### ISSUE TITLE
Database taking up too much space

### ISSUE THREAD

**Issue by simoneb** [nearform/zoom-shuffle-bot#361]
It looks like the database is storing more data than necessary. See billing from GCP:

![image](https://user-images.githubusercontent.com/20181/218708494-a61e0c47-aaaf-4560-9f20-0dc3618e16cc.png)

This suggests that we're not cleaning up data that should probably not be there after a meeting has ended.

**Comment by RomuloVitoi** [comment]
@simoneb that is basically the price of the running instance, for storage we only have 10 GB provisioned which is the minimum and we're only using < 80 MB of that. To reduce costs we would need to reduce the DB tier, we could use share instances since the workload on these are minimal, changing the instance type to `db-f1-micro` would reduce the billing to EUR 8.62/mo

**Comment by simoneb** [comment]
Thanks for figuring this out quickly. Do you know if there's a reason why we went for a larger instance? Can we smoothly downgrade? Is it done manually or do we have IAC? If so, we should do it with IAC

**Comment by simoneb** [comment]
No need to achieve zero downtime, we can make the change manually and reflect it in the workflow so future deployments won't mess anything up.

**Comment by simoneb** [comment]
I've made the necessary changes both in GCP and the workflow code to use the smallest instance available (db-f1-micro)
